### ISSUE TITLE
Moving to a page that's higher than the window has it start out scrolled to bottom

### ISSUE THREAD

**Issue by marijnh** [maryrosecook/codelauren#63]
The reader will probably want to start at the top of the page, but first has to scroll up. I'm using the links with arrows at the bottom of the pages to move around. Chrome 45.

**Comment by maryrosecook** [comment]
Oh blast I thought I fixed this! I’ll look into it.  Thanks a lot for submitting!

**Comment by maryrosecook** [comment]
Hmm this is strange.  I intentionally implemented position memorisation for pages under these circumstances.  Is this what you're seeing?

1. Scroll down a page that is longer than the height of the window.
2. Click the next or previous arrow at the bottom of the page.
3. Click the back button in the browser.
4. You return to the scrolled-down position of the page in step 1.

**Comment by marijnh** [comment]
I don't remember exactly what I did, it may well be that I was just surprised by the persistent scroll positions. If that's intentional, let's just close this until someone else complains.

**Comment by maryrosecook** [comment]
OK cool - thanks!
